spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zswebmysqldbstaging.mysql.database.azure.com:3306/zoftsite?useSSL=true
    username: mysqlstagingdb
    password: Z0ftwebS1te

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
  mvc:
    pathmatch:
      matching:
        strategy:ant-path-matcher
        
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=zswebblob1staging;AccountKey=QZZ32Khv0Ebh0t60/n/+2dbeLGgBxpnV0vF2TfJWC7B5jUYmnsYSxtMDzn8rIaZHvj+V2caIxwVQ+AStfnQ2UQ==;EndpointSuffix=core.windows.net
  blob:
    container-name: images